apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: syriail/udagram-api-feed:v4
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: POSTGRES_DATABASE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: AWS_PROFILE
            - name: AWS_MEDIA_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: AWS_MEDIA_BUCKET
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: URL
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
